### ISSUE TITLE
association about WAVSEP and sectoolmarket vulnerabilities classify

### ISSUE THREAD

**Issue by qux-bbb** [sectooladdict/wavsep#8]
At http://sectoolmarket.com/price-and-feature-comparison-of-web-application-scanners-unified-list.html  
There are 6 kinds of vulnerabilities, and one of them is 'Backup'  vulnerability.  
I want know which vulnerabilities belong to 'Backup'  vulnerability on WAVSEP.

**Comment by qux-bbb** [comment]
I used a old version. Sorry!

**Comment by sectooladdict** [comment]
:)
